spring:
  application:
    name: elitebet
  docker:
    compose:
      enabled: false
  flyway:
    enabled: true
    create-schemas: true
    schemas: elitebet
    default-schema: elitebet
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        default_schema: elitebet

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0

server:
  shutdown: graceful

logging:
  pattern:
    level: "%5p [correlationId:%X{correlationId:-} userId:%X{userId:-}]"
