package com.okemwag.elitebet.shared.exception;

public enum ErrorCode {
	INTERNAL_ERROR,
	VALIDATION_ERROR,
	MALFORMED_REQUEST,
	UNAUTHORIZED,
	NOT_FOUND,
	CONFLICT,
	FORBIDDEN,
	BUSINESS_RULE_VIOLATION,
	EXTERNAL_INTEGRATION_ERROR,
	RATE_LIMIT_EXCEEDED
}
